#!/bin/bash
curl https://zombsroyale.io/asset/build/UnityLoader.js -o asset/build/UnityLoader.js
curl https://zombsroyale.io/asset/build/webgl.data.unityweb -o asset/build/webgl.data.unityweb
curl https://zombsroyale.io/asset/build/webgl.wasm.code.unityweb -o asset/build/webgl.wasm.code.unityweb
curl https://zombsroyale.io/asset/build/webgl.wasm.framework.unityweb -o asset/build/webgl.wasm.framework.unityweb

curl 'https://raw.githack.com/purge' --data-binary 'files=https%3A%2F%2Frawcdn.githack.com%2Fscheng123321%2Ftmm-html5-cdn4%2Fmaster%2Fzombsroyale%2F%0Ahttps%3A%2F%2Frawcdn.githack.com%2Fscheng123321%2Ftmm-html5-cdn4%2Fmaster%2Fzombsroyale%2Findex.html%0Ahttps%3A%2F%2Frawcdn.githack.com%2Fscheng123321%2Ftmm-html5-cdn4%2Fmaster%2Fzombsroyale%2Fasset%2Fbuild%2FUnityLoader.js%0Ahttps%3A%2F%2Frawcdn.githack.com%2Fscheng123321%2Ftmm-html5-cdn4%2Fmaster%2Fzombsroyale%2Fasset%2Fbuild%2Fwebgl.data.unityweb%0Ahttps%3A%2F%2Frawcdn.githack.com%2Fscheng123321%2Ftmm-html5-cdn4%2Fmaster%2Fzombsroyale%2Fasset%2Fbuild%2Fwebgl.wasm.code.unityweb%0Ahttps%3A%2F%2Frawcdn.githack.com%2Fscheng123321%2Ftmm-html5-cdn4%2Fmaster%2Fzombsroyale%2Fasset%2Fbuild%2Fwebgl.wasm.framework.unityweb'