(function(){
/*
 JavaScript Cookie v2.2.0
 https://github.com/js-cookie/js-cookie

 Copyright 2006, 2015 Klaus Hartl & Fagner Brack
 Released under the MIT license
*/
(function(){function h(r,n,f){function c(b,d){if(!n[b]){if(!r[b]){var a="function"==typeof require&&require;if(!d&&a)return a(b,!0);if(e)return e(b,!0);d=Error("Cannot find module '"+b+"'");throw d.code="MODULE_NOT_FOUND",d;}d=n[b]={exports:{}};r[b][0].call(d.exports,function(a){return c(r[b][1][a]||a)},d,d.exports,h,r,n,f)}return n[b].exports}for(var e="function"==typeof require&&require,d=0;d<f.length;d++)c(f[d]);return c}return h})()({1:[function(h,r,n){(function(f){var c=!1;"function"===typeof define&&
define.amd&&(define(f),c=!0);"object"===typeof n&&(r.exports=f(),c=!0);if(!c){var e=window.Cookies,d=window.Cookies=f();d.noConflict=function(){window.Cookies=e;return d}}})(function(){function f(){for(var e=0,d={};e<arguments.length;e++){var b=arguments[e],l;for(l in b)d[l]=b[l]}return d}function c(e){function d(b,l,a){if("undefined"!==typeof document){if(1<arguments.length){a=f({path:"/"},d.defaults,a);if("number"===typeof a.expires){var c=new Date;c.setMilliseconds(c.getMilliseconds()+864E5*a.expires);
a.expires=c}a.expires=a.expires?a.expires.toUTCString():"";try{var g=JSON.stringify(l);/^[\{\[]/.test(g)&&(l=g)}catch(v){}l=e.write?e.write(l,b):encodeURIComponent(String(l)).replace(/%(23|24|26|2B|3A|3C|3E|3D|2F|3F|40|5B|5D|5E|60|7B|7D|7C)/g,decodeURIComponent);b=encodeURIComponent(String(b));b=b.replace(/%(23|24|26|2B|5E|60|7C)/g,decodeURIComponent);b=b.replace(/[\(\)]/g,escape);g="";for(var p in a)a[p]&&(g+="; "+p,!0!==a[p]&&(g+="="+a[p]));return document.cookie=b+"="+l+g}b||(g={});p=document.cookie?
document.cookie.split("; "):[];for(var t=/(%[0-9A-Z]{2})+/g,m=0;m<p.length;m++){var k=p[m].split("="),q=k.slice(1).join("=");this.json||'"'!==q.charAt(0)||(q=q.slice(1,-1));try{c=k[0].replace(t,decodeURIComponent);q=e.read?e.read(q,c):e(q,c)||q.replace(t,decodeURIComponent);if(this.json)try{q=JSON.parse(q)}catch(v){}if(b===c){g=q;break}b||(g[c]=q)}catch(v){}}return g}}d.set=d;d.get=function(b){return d.call(d,b)};d.getJSON=function(){return d.apply({json:!0},[].slice.call(arguments))};d.defaults=
{};d.remove=function(b,c){d(b,"",f(c,{expires:-1}))};d.withConverter=c;return d}return c(function(){})})},{}],2:[function(h,r,n){var f=[];for(h=0;256>h;++h)f[h]=(h+256).toString(16).substr(1);r.exports=function(c,e){e=e||0;return f[c[e++]]+f[c[e++]]+f[c[e++]]+f[c[e++]]+"-"+f[c[e++]]+f[c[e++]]+"-"+f[c[e++]]+f[c[e++]]+"-"+f[c[e++]]+f[c[e++]]+"-"+f[c[e++]]+f[c[e++]]+f[c[e++]]+f[c[e++]]+f[c[e++]]+f[c[e++]]}},{}],3:[function(h,r,n){var f="undefined"!=typeof crypto&&crypto.getRandomValues.bind(crypto)||
"undefined"!=typeof msCrypto&&msCrypto.getRandomValues.bind(msCrypto);if(f){var c=new Uint8Array(16);r.exports=function(){f(c);return c}}else{var e=Array(16);r.exports=function(){for(var d=0,b;16>d;d++)0===(d&3)&&(b=4294967296*Math.random()),e[d]=b>>>((d&3)<<3)&255;return e}}},{}],4:[function(h,r,n){var f=h("./lib/rng"),c=h("./lib/bytesToUuid"),e,d,b=0,l=0;r.exports=function(a,u,g){g=u&&g||0;var p=u||[];a=a||{};var t=a.node||e,m=void 0!==a.clockseq?a.clockseq:d;if(null==t||null==m){var k=f();null==
t&&(t=e=[k[0]|1,k[1],k[2],k[3],k[4],k[5]]);null==m&&(m=d=(k[6]<<8|k[7])&16383)}var k=void 0!==a.msecs?a.msecs:(new Date).getTime(),q=void 0!==a.nsecs?a.nsecs:l+1,h=k-b+(q-l)/1E4;0>h&&void 0===a.clockseq&&(m=m+1&16383);(0>h||k>b)&&void 0===a.nsecs&&(q=0);if(1E4<=q)throw Error("uuid.v1(): Can't create more than 10M uuids/sec");b=k;l=q;d=m;k+=122192928E5;a=(1E4*(k&268435455)+q)%4294967296;p[g++]=a>>>24&255;p[g++]=a>>>16&255;p[g++]=a>>>8&255;p[g++]=a&255;a=k/4294967296*1E4&268435455;p[g++]=a>>>8&255;
p[g++]=a&255;p[g++]=a>>>24&15|16;p[g++]=a>>>16&255;p[g++]=m>>>8|128;p[g++]=m&255;for(m=0;6>m;++m)p[g+m]=t[m];return u?u:c(p)}},{"./lib/bytesToUuid":2,"./lib/rng":3}],5:[function(h,r,n){var f=this&&this.__extends||function(){var d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(a,d){a.__proto__=d}||function(a,d){for(var b in d)d.hasOwnProperty(b)&&(a[b]=d[b])};return function(a,b){function c(){this.constructor=a}d(a,b);a.prototype=null===b?Object.create(b):(c.prototype=b.prototype,
new c)}}();Object.defineProperty(n,"__esModule",{value:!0});var c=h("./feature-detection"),e=h("./cookies"),d=h("./encoding"),b;(function(b){function a(b){if(!document.body)return setTimeout(a.bind(null,b),1);document.body.appendChild(b)}var l=c.FeatureDetection.Detect,g=e.ApolloCookies.CookieManager,p=d.Encoding.Base64;b=function(b){function a(a){void 0===a&&(a={});var d=new l("page-view"),c=new g;return b.call(this,"page-view",d,c,a)||this}f(a,b);return a}(function(){function a(a,b,d,c){this.detector=
b;this.cookies=d;this.start=Date.now();this.visitorId=this.cookies.getVisitorId();this.sessionId=this.cookies.getSessionId();this.event=a;this.extraData=c}a.prototype.pushData=function(a,b){this.extraData[a]=b};a.prototype.send=function(){this.mergeExtraData();this.preparePayload();var a=JSON.stringify(this.payload),a=p.encode(a);this.sendCors(a)};a.prototype.sendCors=function(a){try{var b=new (XMLHttpRequest||ActiveXObject)("MSXML2.XMLHTTP.3.0");b.open("POST","//apollo.miniclip.com/v1/data/push",!0);b.withCredentials=
!0;b.setRequestHeader("Content-type","application/x-www-form-urlencoded");b.setRequestHeader("X-Requested-With","XMLHttpRequest");b.setRequestHeader("X-MC-AClient","1.0");b.onreadystatechange=function(){if(4===this.readyState){var a=JSON.parse(this.responseText);a&&1==a.success||window.console&&console.log(b.responseText)}};b.send(a)}catch(q){window.console&&console.log("EXCEPTION:")&&console.log(q)}};a.prototype.preparePayload=function(){this.payload={start:this.start,finish:Date.now(),load:window.performance.now(),
event:this.event,visitorId:this.visitorId,sessionId:this.sessionId,client:window.mc_ap_pv_c_n,origin:window.location.href,referrer:document.referrer,features:this.detector.getFeatures(),data:this.extraData}};a.prototype.mergeExtraData=function(){this.mergeClientData();this.mergeServerData()};a.prototype.mergeClientData=function(){if(window.MCApolloPageView.hasOwnProperty("q"))for(var a=0;a<window.MCApolloPageView.q.length;++a){var b=window.MCApolloPageView.q[a];this.extraData[b[0]]=b[1]}};a.prototype.mergeServerData=
function(){if(window.hasOwnProperty("mc_apvd"))try{var a=JSON.parse(p.decode(window.mc_apvd));if(a&&"object"===typeof a)for(var b in a)a.hasOwnProperty(b)&&(this.extraData[b]=a[b])}catch(q){}};return a}());window.mc_ap_pv_e=new b;b=document.createElement("script");b.text="if(document.readyState=='interactive'||document.readyState=='complete'){mc_ap_pv_e.send();}else{window.addEventListener('DOMContentLoaded',function(){mc_ap_pv_e.send();});}";a(b)})(b||(b={}))},{"./cookies":6,"./encoding":7,"./feature-detection":8}],
6:[function(h,r,n){Object.defineProperty(n,"__esModule",{value:!0});var f=h("uuid/v1"),c=h("js-cookie"),e=h("./encoding");(function(d){var b=e.Encoding.Base64,l=function(){function a(){this.VISITOR_ID_COOKIE_NAME="MCA_VID";this.SESSION_ID_COOKIE_NAME="MCA_SID";this.setVisitorId();this.setSessionId()}a.prototype.getVisitorId=function(){return this.visitorId};a.prototype.getSessionId=function(){return this.sessionId};a.prototype.setSessionId=function(){this.sessionId=c.get(this.SESSION_ID_COOKIE_NAME);
this.sessionId||(this.sessionId=b.encode(f()));c.set(this.SESSION_ID_COOKIE_NAME,this.sessionId,{expires:1/48})};a.prototype.setVisitorId=function(){this.visitorId=c.get(this.VISITOR_ID_COOKIE_NAME);this.visitorId||(this.visitorId=b.encode(f()),c.set(this.VISITOR_ID_COOKIE_NAME,this.visitorId,{expires:36500}))};return a}();d.CookieManager=l})(n.ApolloCookies||(n.ApolloCookies={}))},{"./encoding":7,"js-cookie":1,"uuid/v1":4}],7:[function(h,r,n){Object.defineProperty(n,"__esModule",{value:!0});(function(f){var c=
function(){function c(){}c.encode=function(d){var b="",l=0;for(d=c.utf8_encode(d);l<d.length;){var a=d.charCodeAt(l++);var e=d.charCodeAt(l++);var g=d.charCodeAt(l++);var f=a>>2;a=(a&3)<<4|e>>4;var h=(e&15)<<2|g>>6;var m=g&63;isNaN(e)?h=m=64:isNaN(g)&&(m=64);b=b+c.keyStr.charAt(f)+c.keyStr.charAt(a)+c.keyStr.charAt(h)+c.keyStr.charAt(m)}return b};c.decode=function(d){var b="",l=0;for(d=d.replace(/[^A-Za-z0-9\+\/\=]/g,"");l<d.length;){var a=c.keyStr.indexOf(d.charAt(l++));var e=c.keyStr.indexOf(d.charAt(l++));
var g=c.keyStr.indexOf(d.charAt(l++));var f=c.keyStr.indexOf(d.charAt(l++));a=a<<2|e>>4;e=(e&15)<<4|g>>2;var h=(g&3)<<6|f;b+=String.fromCharCode(a);64!=g&&(b+=String.fromCharCode(e));64!=f&&(b+=String.fromCharCode(h))}return b=c.utf8_decode(b)};c.utf8_encode=function(d){d=d.replace(/\r\n/g,"\n");for(var b="",c=0;c<d.length;c++){var a=d.charCodeAt(c);128>a?b+=String.fromCharCode(a):(127<a&&2048>a?b+=String.fromCharCode(a>>6|192):(b+=String.fromCharCode(a>>12|224),b+=String.fromCharCode(a>>6&63|128)),
b+=String.fromCharCode(a&63|128))}return b};c.utf8_decode=function(c){for(var b="",d=0,a,e,g;d<c.length;)a=c.charCodeAt(d),128>a?(b+=String.fromCharCode(a),d++):191<a&&224>a?(e=c.charCodeAt(d+1),b+=String.fromCharCode((a&31)<<6|e&63),d+=2):(e=c.charCodeAt(d+1),g=c.charCodeAt(d+2),b+=String.fromCharCode((a&15)<<12|(e&63)<<6|g&63),d+=3);return b};c.keyStr="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";return c}();f.Base64=c})(n.Encoding||(n.Encoding={}))},{}],8:[function(h,r,n){Object.defineProperty(n,
"__esModule",{value:!0});(function(f){var c={create:function(c){return document.createElement(c)},old:!!/(Android\s(1.|2.))|(Silk\/1.)/i.test(navigator.userAgent),pfx:function(){var c=document.createElement("dummy").style,b=["Webkit","Moz","O","ms"],e={};return function(a){if("undefined"===typeof e[a]){var d=a.charAt(0).toUpperCase()+a.substr(1),d=(a+" "+b.join(d+" ")+d).split(" ");e[a]=null;for(var g in d)if(void 0!==c[d[g]]){e[a]=d[g];break}}return e[a]}}()},e=function(){function d(b){this.plugin=
!1;var d=navigator.userAgent,a=window.screen.availWidth*window.devicePixelRatio+"x"+window.screen.availHeight*window.devicePixelRatio,e=this.detectFlashVersion().pv,g=!c.old&&null!==c.pfx("perspective"),f=!c.old&&null!==c.pfx("transformOrigin"),h=null!==c.pfx("transition"),m=!!window.addEventListener,k=!!document.querySelectorAll,n=!!window.matchMedia,r="DeviceMotionEvent"in window,x="DeviceOrientationEvent"in window,y="contextMenu"in document.documentElement&&"HTMLMenuItemElement"in window,z="classList"in
document.documentElement,A="placeholder"in c.create("input"),B=window.history&&"pushState"in window.history,C=!!document.createElementNS&&!!document.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect,D=!!("ontouchstart"in window||window.navigator&&window.navigator.msPointerEnabled&&window.MSGesture||window.DocumentTouch&&document instanceof DocumentTouch),E="async"in c.create("script"),F="defer"in c.create("script"),G="srcset"in c.create("img"),H="sizes"in c.create("img"),I="HTMLPictureElement"in
window,J=navigator.javaEnabled();try{localStorage.setItem("x","x");localStorage.removeItem("x");var w=!0}catch(L){w=!1}this.Features={userAgent:d,deviceResolution:a,flashVersion:e,css3DTransform:g,cssTransform:f,cssTransition:h,addEventListener:m,querySelectorAll:k,matchMedia:n,deviceMotion:r,deviceOrientation:x,contextMenu:y,classList:z,placeholder:A,historyAPI:B,serviceWorker:"serviceWorker"in navigator,svg:C,touch:D,async:E,defer:F,geolocation:"geolocation"in navigator,srcset:G,sizes:H,pictureElement:I,
cors:!0,java_enabled:J,localStorage:w,viewportUnit:function(a){try{return a.style.width="1vw",""!==a.style.width}catch(K){return!1}}(c.create("dummy")),remUnit:function(a){try{return a.style.width="1rem",""!==a.style.width}catch(K){return!1}}(c.create("dummy")),canvas:function(a){return!(!a.getContext||!a.getContext("2d"))}(c.create("canvas")),webGL:function(a){if(window.WebGLRenderingContext){for(var b=["webgl","experimental-webgl","moz-webgl","webkit-3d"],c=!1,d=0;4>d;d++)try{if((c=a.getContext(b[d]))&&
"function"==typeof c.getParameter)return"enabled"}catch(M){}return"disabled"}return"unavailable"}(c.create("canvas"))};this.event=b}d.prototype.getFeatures=function(){return"page-view"===this.event?this.Features:{}};d.prototype.toInt=function(b){return parseInt(b,10)};d.prototype.detectFlashVersion=function(){var b=navigator,c=document,a=window,c="undefined"!==typeof c.getElementById&&"undefined"!==typeof c.getElementsByTagName&&"undefined"!==typeof c.createElement,d=b.userAgent.toLowerCase(),e=b.platform.toLowerCase(),
f=e?/win/.test(e):/win/.test(d),e=e?/mac/.test(e):/mac/.test(d),d=/webkit/.test(d)?parseFloat(d.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):!1,h="Microsoft Internet Explorer"===b.appName,m=[0,0,0],k=null;if("undefined"!==typeof b.plugins&&"object"===typeof b.plugins["Shockwave Flash"])(k=b.plugins["Shockwave Flash"].description)&&"undefined"!==typeof b.mimeTypes&&b.mimeTypes["application/x-shockwave-flash"]&&b.mimeTypes["application/x-shockwave-flash"].enabledPlugin&&(this.plugin=!0,h=!1,k=k.replace(/^.*\s+(\S+\s+\S+$)/,
"$1"),m[0]=this.toInt(k.replace(/^(.*)\..*$/,"$1")),m[1]=this.toInt(k.replace(/^.*\.(.*)\s.*$/,"$1")),m[2]=/[a-zA-Z]/.test(k)?this.toInt(k.replace(/^.*[a-zA-Z]+(.*)$/,"$1")):0);else if("undefined"!==typeof a.ActiveXObject)try{if(k=(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version"))h=!0,k=k.split(" ")[1].split(","),m=[this.toInt(k[0]),this.toInt(k[1]),this.toInt(k[2])]}catch(q){}return{w3:c,pv:m,wk:d,ie:h,win:f,mac:e}};return d}();f.Detect=e})(n.FeatureDetection||(n.FeatureDetection=
{}))},{}]},{},[5]);
}).call(this)
